_core:
  default_config_hash: G8QQmvYdIX4fGt1SxVZIFa0KjWFS4FbLlNlt6N19qIM
system_match: null
system_prefix: null
system_regex: null
system_negate: false
layout_match: null
layout_prefix: null
layout_regex: null
layout_negate: false
